name: Deploy Website to S3

on:
  push:
    branches:
      - main  # Runs every time you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Deploy all files from repo root to S3
      - name: Upload website to S3
        run: aws s3 sync . s3://mys3bucket890722 --delete --exclude ".git/*" --exclude ".github/*"
